### ISSUE TITLE
get version number

### ISSUE THREAD

**Issue by MDSergioMD** [criteo/android-publisher-sdk#120]
Hi, is there any way to get the version number at runtime ?

**Comment by TurpIF** [comment]
Hi,

For now it is not possible to get it at runtime via the SDK, but we're planning it.

Meanwhile you can inject it in your `BuidConfig` class with your `build.gradle` file.
Please see this example: https://github.com/criteo/android-publisher-sdk-mopub-adapters/blob/master/mediation/build.gradle#L51. It is injecting a `BuildConfig.SDK_VERSION` constant accessible from the code.

**Comment by MDSergioMD** [comment]
Thank you very much for the reply and help

**Comment by TurpIF** [comment]
Also, I'm wondering why do you need the version during the runtime ?

**Comment by MDSergioMD** [comment]
Hi, we use it to report the version number of our ad providers to our
servers.

**Comment by Amokrane** [comment]
Thanks for the information @MDSergioMD. You will be able to get the version number at runtime with the next version (4.0).

**Comment by MDSergioMD** [comment]
Great news, thank you
