### ISSUE TITLE
Use newest Picasso version

### ISSUE THREAD

**Issue by petras-vinted** [criteo/android-publisher-sdk#138]
https://github.com/criteo/android-publisher-sdk/blob/e9148f6a56222daa6c78b1734591e8023f752b93/buildSrc/src/main/java/Deps.kt#L169

Version that you are currently using does not support AndroidX. We would like to get rid of Android Support dependencies to be able to remove Jetifier and improve build times.

https://github.com/square/picasso/tree/2.8

**Comment by Amokrane** [comment]
Hi @petras-vinted, thank you for bringing this to our attention. We will try to update Picasso to 2.8 indeed for the next `4.1.0` release.

**Comment by Amokrane** [comment]
The change was merged: https://github.com/criteo/android-publisher-sdk/pull/153
It will be released with the next version: `4.1.0`.
