### ISSUE TITLE
How to setup crt_cpm and crt_size key values with Google Ad Manager

### ISSUE THREAD

**Issue by shukerullah** [criteo/android-publisher-sdk#224]
I have already setup Ad server. I have followed all the required steps mention in the [document](https://publisherdocs.criteotilt.com/app/android/app-bidding/google-ad-manager/#ad-server-setup). But Criteo team is saying that there are no key values in the GAM calls after the bid response, here is their response:

`“Looks like there are no Criteo key values in the GAM calls after the bid responses. Charles log is attached. It seems something doesn't work properly and we are not able to see bid keywords in the ad requests.”`

Criteo team has also confirmed that Ad Server is setup correctly. Then why they don't see these key values, do I need to send custom targeting (**crt_cpm** and **crt_size**) programmatically? If yes, then how to get values for **crt_cpm**?

**Comment by shukerullah** [comment]
I get **price** from Publisher Bid and set these values for **crt_cpm**. let me know if i missed anything. Here is my code:
```
public void onResponse(@Nullable Bid bid) {
    ...

    final Context context = getContext();
    int width = adView.getAdSize().getWidthInPixels(context);
    int height = adView.getAdSize().getHeightInPixels(context);

    adRequestBuilder.addCustomTargeting("crt_size", width + "x" + height);
    adRequestBuilder.addCustomTargeting("crt_cpm", bid.getPrice() + "");

    ...
}
```

**Comment by irwansetiawan** [comment]
Hello, you **do not** have to send custom targeting programmatically, `enrichAdObjectWithBid()` will. Make sure you have called `enrichAdObjectWithBid()` in your code.

As per [documentation](https://publisherdocs.criteotilt.com/app/android/app-bidding/google-ad-manager/#set-criteo-bids-on-publisheradrequest-builder-object):
```
// load Criteo bids
Criteo.getInstance().loadBid(bannerAdUnit, new BidResponseListener() {
    @Override
    public void onResponse(@Nullable Bid bid) {
        // Your existing Ad manager request builder
        PublisherAdRequest.Builder builder = new PublisherAdRequest.Builder();

        if (bid != null) {
            Criteo.getInstance().enrichAdObjectWithBid(builder, bid);
        }

        // load Banner ad after Criteo bid is loaded
        PublisherAdRequest request = builder.build();
        mPublisherAdView.loadAd(request);
    }
});
```

**Comment by shukerullah** [comment]
For me bid is always null.

**Comment by irwansetiawan** [comment]
Criteo doesn't always respond with a bid, depending on different factors. You may want to test using test ad unit IDs that will always return test bids. https://publisherdocs.criteotilt.com/app/android/testing/#test-ad-unit-ids

**Comment by irwansetiawan** [comment]
@shukerullah are you able to finally get key values and complete the integration?

**Comment by shukerullah** [comment]
Yes, @irwansetiawan thank you
